# -*- coding: UTF-8 -*-
# values for the MakeScript.py app
PROMPT_LIST_LABEL='Prompt List:'
PROMPT_LIST_BUTTON='...'
LIST_OF_SCRIPTS_LABEL='List of scripts:'
OUTPUT_FILE_LABEL='Output File:'
APPLICATION_TITLE='MAKE SCRIPTS'
BUTTON_LISTBOX_DELETE='Delete Selected Scripts'
BUTTON_LISTBOX_CLEAR='Clear Scripts'
OUTPUT_FILE_BUTTON = '...'
BUTTON_LISTBOX_ADD='Add scripts...'
GENERATE_BUTTON='GENERATE!'
LEFT_HEADER = "&F"
CENTER_HEADER = "&A"
RIGHT_HEADER = "&D &T"
LEFT_FOOTER= '\xA9 Your Name Here. All rights reserved.'
CENTER_FOOTER = ""
RIGHT_FOOTER = "Page &P of &N"
BUTTON_LOAD_SCRIPTFILE="Load a script file..."
TEXT_MATCH_CASE = 'Match Case?'
TEXT_DESC_FONT = 'Set font to 8 for Content cell?'
FONT_SIZE=8
COLUMN_WIDTH_TEXT = 70
COLUMN_WIDTH_PAGE = 10
COLUMN_WIDTH_SPEAKER = 10
COLUMN_WIDTH_CONTENTS_SCRIPT_NUM=10
LEFT_MARGIN=0.5
RIGHT_MARGIN=0.5
CELL_FONT_BOLD = "Bold"
CELL_COLOR_GRAY = 15
TITLE_ROW = 2
CALLER_ROW_TEXT = 'Caller'

